version: "3"

dotenv:
  - .env

vars:
  IMAGE_PREFIX: prod

tasks:
  default:
    cmds:
      - task --list

  pre:commit:
    desc: "Run pre commit checks"
    deps:
      - lint
      - docs:swagger

  http:dev:
    desc: "Run HTTP dev server"
    cmds:
      - go run ./cmd/http/main.go

  http:build:
    desc: "Build HTTP binary"
    cmds:
      - go build -ldflags="-s -w" -o ./http ./cmd/http/main.go

  http:run:
    desc: "Run HTTP binary"
    cmds:
      - ./http

  lint:
    desc: "Lint Go code"
    cmds:
      - golangci-lint run --config .golangci.yml --fix

  docs:swagger:
    desc: "Generate Swagger docs"
    cmds:
      - swag init -g ./internal/handler/http/handler.go --parseDependency

  migrations:create:
    desc: "Create new migration"
    cmds:
      - goose create {{.CLI_ARGS}} sql

  migrations:up:
    desc: "Apply migrations"
    cmds:
      - goose {{if .CLI_ARGS}}up-to {{.CLI_ARGS}}{{else}}up{{end}}

  migrations:down:
    desc: "Rollback migrations"
    cmds:
      - goose {{if .CLI_ARGS}}down-to {{.CLI_ARGS}}{{else}}down{{end}}
