// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/_hc": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_monitoring_health_check.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/improvements/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "improvement"
                ],
                "summary": "improvement generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_improvement_improvement_generate.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/responses/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "response"
                ],
                "summary": "response generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_response_response_generate.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/summaries/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "summary"
                ],
                "summary": "summary generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_summary_summary_generate.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_eerzho_telegram_ai_pkg_sse.Event": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "retry": {
                    "description": "milliseconds",
                    "type": "integer"
                }
            }
        },
        "httpjson.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpjson.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpjson.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_improvement_improvement_generate.Input": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_monitoring_health_check.Output": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_response_response_generate.Input": {
            "type": "object",
            "required": [
                "language",
                "messages",
                "owner"
            ],
            "properties": {
                "language": {
                    "type": "string",
                    "maxLength": 2,
                    "minLength": 2
                },
                "messages": {
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_response_response_generate.InputMessage"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/internal_response_response_generate.InputUser"
                }
            }
        },
        "internal_response_response_generate.InputMessage": {
            "type": "object",
            "required": [
                "date",
                "sender",
                "text"
            ],
            "properties": {
                "date": {
                    "type": "integer"
                },
                "sender": {
                    "$ref": "#/definitions/internal_response_response_generate.InputUser"
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_response_response_generate.InputUser": {
            "type": "object",
            "required": [
                "chat_id",
                "name"
            ],
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_summary_summary_generate.Input": {
            "type": "object",
            "required": [
                "language",
                "messages",
                "owner"
            ],
            "properties": {
                "language": {
                    "type": "string",
                    "maxLength": 2,
                    "minLength": 2
                },
                "messages": {
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_summary_summary_generate.InputMessage"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/internal_summary_summary_generate.InputUser"
                }
            }
        },
        "internal_summary_summary_generate.InputMessage": {
            "type": "object",
            "required": [
                "date",
                "sender",
                "text"
            ],
            "properties": {
                "date": {
                    "type": "integer"
                },
                "sender": {
                    "$ref": "#/definitions/internal_summary_summary_generate.InputUser"
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_summary_summary_generate.InputUser": {
            "type": "object",
            "required": [
                "chat_id",
                "name"
            ],
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        }
    },
    "externalDocs": {
        "description": "GitHub",
        "url": "https://github.com/eerzho/telegram_ai"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "TelegramAI",
	Description:      "Telegram with AI features",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
