// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/_hc": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_monitoring_health_check.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/improvements/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "improvement"
                ],
                "summary": "improvement generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_improvement_generate_improvement.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/responses/{user_id}/{chat_id}/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "response"
                ],
                "summary": "response generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_response_generate_response.Input"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ChatID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_response_generate_response.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/settings": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "create setting",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_setting_create_setting.Input"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_setting_create_setting.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/settings/{user_id}/{chat_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get setting",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ChatID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_setting_get_setting.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "update setting",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_setting_update_setting.Input"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ChatID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_setting_update_setting.Output"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "delete setting",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ChatID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        },
        "/v1/summaries/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "summary"
                ],
                "summary": "summary generate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_summary_generate_summary.Input"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpjson.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_eerzho_telegram_ai_internal_domain.ReactionType": {
            "type": "string",
            "enum": [
                "ok",
                "like",
                "dislike"
            ],
            "x-enum-varnames": [
                "ReactionTypeOK",
                "ReactionTypeLike",
                "ReactionTypeDislike"
            ]
        },
        "github_com_eerzho_telegram_ai_internal_domain.ResponseType": {
            "type": "string",
            "enum": [
                "message",
                "reaction",
                "skip"
            ],
            "x-enum-varnames": [
                "ResponseTypeMessage",
                "ResponseTypeReaction",
                "ResponseTypeSkip"
            ]
        },
        "github_com_eerzho_telegram_ai_pkg_sse.Event": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "retry": {
                    "description": "milliseconds",
                    "type": "integer"
                }
            }
        },
        "httpjson.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpjson.ErrorDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpjson.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_improvement_generate_improvement.Input": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_monitoring_health_check.Output": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_response_generate_response.Input": {
            "type": "object",
            "required": [
                "messages",
                "owner"
            ],
            "properties": {
                "messages": {
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_response_generate_response.InputMessage"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/internal_response_generate_response.InputUser"
                }
            }
        },
        "internal_response_generate_response.InputMessage": {
            "type": "object",
            "required": [
                "date",
                "sender",
                "text"
            ],
            "properties": {
                "date": {
                    "type": "integer"
                },
                "sender": {
                    "$ref": "#/definitions/internal_response_generate_response.InputUser"
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_response_generate_response.InputUser": {
            "type": "object",
            "required": [
                "chat_id",
                "name"
            ],
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_response_generate_response.Output": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "reaction_type": {
                    "$ref": "#/definitions/github_com_eerzho_telegram_ai_internal_domain.ReactionType"
                },
                "type": {
                    "$ref": "#/definitions/github_com_eerzho_telegram_ai_internal_domain.ResponseType"
                }
            }
        },
        "internal_setting_create_setting.Input": {
            "type": "object",
            "required": [
                "chat_id",
                "user_id"
            ],
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "style": {
                    "type": "string",
                    "maxLength": 500
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_setting_create_setting.Output": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_setting_get_setting.Output": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_setting_update_setting.Input": {
            "type": "object",
            "properties": {
                "style": {
                    "type": "string",
                    "maxLength": 500
                }
            }
        },
        "internal_setting_update_setting.Output": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_summary_generate_summary.Input": {
            "type": "object",
            "required": [
                "language",
                "messages",
                "owner"
            ],
            "properties": {
                "language": {
                    "type": "string",
                    "maxLength": 2,
                    "minLength": 2
                },
                "messages": {
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/internal_summary_generate_summary.InputMessage"
                    }
                },
                "owner": {
                    "$ref": "#/definitions/internal_summary_generate_summary.InputUser"
                }
            }
        },
        "internal_summary_generate_summary.InputMessage": {
            "type": "object",
            "required": [
                "date",
                "sender",
                "text"
            ],
            "properties": {
                "date": {
                    "type": "integer"
                },
                "sender": {
                    "$ref": "#/definitions/internal_summary_generate_summary.InputUser"
                },
                "text": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_summary_generate_summary.InputUser": {
            "type": "object",
            "required": [
                "chat_id",
                "name"
            ],
            "properties": {
                "chat_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        }
    },
    "externalDocs": {
        "description": "GitHub",
        "url": "https://github.com/eerzho/telegram_ai"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "TelegramAI",
	Description:      "Telegram with AI features",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
